chore: Added documentation for newly added functionality
modelon-community/impact-client-python pull request #125
Opened 2021-12-06 07:57 UTC by abhilash-kumar-nair

2021-12-06 10:37 UTC, efredriksson-modelon requested changes
Nice work documenting the workflows! 🧇 

I am a little worried that we just have a single tutorial and everything is added to it. It would be good if we could break it up and structure it so the user can take the tutorials they are intressted in. I am happy to help. Here is a suggestion on the outline of the tutorials:
 * Setting up the workspace (includes setting up the client also)
 * Choosing analysis type (just add at the end that this class `CustomFunction` will be used as input for creating an experiment)
 * Choosing a model (just a rename of Set up model for analysis)
 * Setup and run an experiment (Contains "2.1 Setting up an experiment" and "Executing the experiment" and would also have to include the code `experiment_definition = experiment_definition.with_modifiers({'PI.k': Range(10, 100, 3)})` mentioning super short that this will make it so the experiment contains 3 cases and then have a reference to the mutli-execution tutorial for more information on how to do this.)
 * Plotting experiment results (re-name of "Plotting the results")
 * Muti-execution experiments (operators and extensions sections included here)
 * Re-executing and updating experiments (what you have written)
 * FMU based workflow (would also contain the relevant part of 'Analysis' explaining what this is about)
 * Logging output for client (rename of Setting logging levels for analysis)
 * Removing FMUs and experiments

Unrelated but would be very nice to fix. The line
`model = workspace.upload_model_library('C:/Model.mo')`
in documentation is not correct. That method does not return anything so you would still need to create the 'model' class for a specific model yourself.

2021-12-06 10:37 UTC, efredriksson-modelon commented on docs/source/tutorial.rst
> +   experiment = workspace.execute(experiment_definition).wait()
Note that you need to update the code snippet for plotting to use `experiment`.

2021-12-06 10:42 UTC, andrewwren-modelon commented on docs/source/tutorial.rst
> +experiment multiple times.
ln 325 time should be plural...
Perhaps:
Subsequent executions will create a new experiment object and as such ill advised for re-execution of the same experiment.

2021-12-06 10:42 UTC, andrewwren-modelon commented on docs/source/tutorial.rst
> +This approach isolate the creation and execution of an experiment as two methods::
isolates?

2021-12-13 12:12 UTC, abhilash-kumar-nair commented
Thanks for review and the good feedback. @efredriksson-modelon , @andrewwren-modelon . Could you please take another look ? Thanks!

2021-12-13 15:38 UTC, efredriksson-modelon requested changes
Nice I think this should be very helpful for users not intressted in only some parts! 🍉🍉🍉

2021-12-13 15:38 UTC, efredriksson-modelon commented on docs/source/muti_execution_experiments.rst
> +The parametrization in the examples above would configure a set of three simulation cases for the fmu with ``3`` equidistant
fmu -> model

2021-12-13 15:38 UTC, efredriksson-modelon commented on docs/source/reexecuting_updating_experiments.rst
> +3. Non-structural parameters - E.g. - 'PI.k' for the Modelica.Blocks.Examples.PID_Controller.
This list is not formatted correctly when I build HTML. Maybe we need an empty line before it?

2021-12-13 15:38 UTC, efredriksson-modelon commented on docs/source/logging_output_for_client.rst
> +should be output by the client can be set by specifying the log level as shown in the code snippet.::
.:: -> ::

2021-12-13 15:38 UTC, efredriksson-modelon commented on docs/source/logging_output_for_client.rst
> +The log is printed to the standard output, normally the terminal window from which the compiler is invoked. The available log levels are
compiler?

2021-12-13 15:38 UTC, efredriksson-modelon commented on docs/source/reexecuting_updating_experiments.rst
> +    experiment_expand = experiment.execute(with_cases=[]).wait()
Maybe add the code line 
experiment = workspace.create_experiment(experiment_definition)

to make it more clear that you run this just after creating the experiment.

2021-12-14 14:34 UTC, abhilash-kumar-nair commented
> Nice I think this should be very helpful for users not intressted in only some parts! 🍉🍉🍉

Thanks again @efredriksson-modelon for the great feedback! I have made the suggested fixes! Could you please taken another quick look? Thanks!

2021-12-14 14:47 UTC, efredriksson-modelon approved these changes
👍

2021-12-15 04:37 UTC, merged