feat: Added possibility to specify result format
modelon-community/impact-client-python pull request #129
Opened 2022-01-18 06:17 UTC by abhilash-kumar-nair

Jira - https://modelonproducts.atlassian.net/browse/WAMS-8882
Code to test
```
from modelon.impact.client import Client

client = Client(url="http://127.0.0.1:8080")
workspace = client.create_workspace("Pop1")

# Choose analysis type
# dynamic = workspace.get_custom_function('steady state')
dynamic = workspace.get_custom_function('dynamic')

# Get model class
model = workspace.get_model("Modelica.Mechanics.Translational.Examples.SignConvention")
# Execute experiment
experiment_definition = model.new_experiment_definition(dynamic)
exp = workspace.execute(experiment_definition).wait()

# Getting the simulated FMU object from the case object
case = exp.get_case('case_1')
result, file_name = case.get_result(format="csv")
with open(file_name, "w") as f:
    f.write(result)
result, file_name = case.get_result(format="mat")
with open(file_name, "wb") as f:
    f.write(result)

```

2022-01-26 15:15 UTC, efredriksson-modelon requested changes
Nice to have also the client implementation mostly done 🥇

2022-01-26 15:15 UTC, efredriksson-modelon commented on modelon/impact/client/sal/service.py
> +    def case_result_get(self, workspace_id, experiment_id, case_id, result_format=None):
default should be `'mat'` instead of `None`

2022-01-26 15:15 UTC, efredriksson-modelon commented on modelon/impact/client/entities.py
> +    def get_result(self, format=None):
default should be `'mat'` instead of `None`

2022-01-31 08:06 UTC, efredriksson-modelon approved these changes
👍 

(But we should not merge this PR until we have made a proper release of the beta branch that can be used for the 1.5 release).

2022-01-31 08:06 UTC, efredriksson-modelon commented on modelon/impact/client/sal/service.py
> +    def _missing_(cls, value):
Very nice!

2022-01-31 08:06 UTC, efredriksson-modelon commented on modelon/impact/client/sal/service.py
> +        format = ResultFormat(result_format)
I think we should do this as early as possible. Consider moving this to the get_result method.

2022-02-11 14:54 UTC, efredriksson-modelon requested changes
I think this one should go to the beta branch. It also needs an update in what API version is accepted (need the new download feature), it will not work with the 1.5 release of impact.

2022-02-17 03:48 UTC, abhilash-kumar-nair commented
> I think this one should go to the beta branch. It also needs an update in what API version is accepted (need the new download feature), it will not work with the 1.5 release of impact.

Ah yes. I have bumped the version range. The MI feature has now been merged https://gitlab.modelon.com/modelon-products/impact/diraction/-/merge_requests/6167. Could you please take another look? Thanks!

2022-02-17 08:13 UTC, efredriksson-modelon requested changes
I think the code looks good still 👍

As this change will make the client not compatible with IM 1.5 I think we should start making beta releases now as we are getting new functionality. So, Ola merges his PR removing locks -> create beta branch from master -> merge this one to the beta branch.

2022-02-17 10:02 UTC, efredriksson-modelon approved these changes
👍

2022-02-17 10:28 UTC, merged