fix: added instructions for non-interactive JHub token authentication
modelon-community/impact-client-python pull request #155
Opened 2022-09-02 12:15 UTC by abhilash-kumar-nair

Customer request - https://github.com/modelon-community/impact-client-python/pull/154

2022-09-02 12:20 UTC, anna-lindholm commented
Looks good, thanks! We might have more feedback on this from other channels which we should also include in the readme, but let's start with this and add a new PR for these.

2022-09-02 12:21 UTC, anna-lindholm approved these changes

2022-09-05 05:35 UTC, abhilash-kumar-nair commented
@anna-lindholm  Thanks for the review! @iakovn  mentioned that JupyterHub always sets the current token into JUPYTERHUB_API_TOKEN environment variable, hence I have update the code and docs to utilize that environment variable when available instead of asking for a token.

2022-09-05 11:30 UTC, iakovn requested changes
Great to have this info up! 🍬 

Please see the minor comments and then I suggest a bit larger edit both in QuickStart and here:
- QuickStart mentions "<impact-domain>" which seems like a non-standard and as such a confusing term. I suggest to explicitly define that impact domain refers to either  MI cloud or on-prem external URL, e.g., https://impact.modelon.cloud, or a local server, i.e., http://127.0.0.1:8080.  The local server address can be used from a notebook running as a part of cloud or on-prem MI installation.
- I suggest the section in the setup to be renamed into "Authentication with MI cloud or on-prem". Proposed text: 

This part of setup is relevant if you are using MI cloud or on-prem installation and would like to utilize external URL, such as https://impact.modelon.cloud. If you rely on the local connection using, e.g., http://127.0.0.1:8080, then skip to the next section.

MI cloud/on-prem is utilizing JupyterHub as a part of the infrastructure. Therefore authentication when connecting via external URL, such as https://impact.modelon.cloutd requires authenticating with JupyterHub gateway. Connection to the external URL can be done from within a notebook running as a part of MI installation. In that case this will be automatic based on the automatically populated JUPYTERHUB_API_TOKEN environment variable. 

If this client library is used from outside of the environment, e.g., from your desktop, then JupyterHub API token needs to be supplied in JUPYTERHUB_API_TOKEN environment variable or interactively. The token can be obtained from https://impact.modelon.cloud/hub/token page or corresponding page in the on-prem installation.

2022-09-05 11:30 UTC, iakovn commented on modelon/impact/client/jupyterhub/authorize.py
> +        else "MODELON_IMPACT_JUPYTERHUB_CLIENT_API_TOKEN",
I suggest to deprecate the use of MODELON_IMPACT_JUPYTERHUB_CLIENT_API_TOKEN. We'll be releasing a major version update anyhow and I see no reason for having two different env vars for the same thing.

2023-05-09 09:22 UTC, abhilash-kumar-nair commented
Changes suggested have been made in other PRs

2023-05-09 09:22 UTC, closed without merging