feat: added possibility to filter experiments for models
modelon-community/impact-client-python pull request #178
Opened 2023-03-14 04:16 UTC by abhilash-kumar-nair

2023-03-14 07:28 UTC, efredriksson-modelon requested changes

2023-03-14 07:28 UTC, efredriksson-modelon commented on tests/impact/client/sal/test_workspace_service.py
> +            f'http://mock-impact.com/api/workspaces/workspace_1/experiments?classPath='
This does not look right, `?classPath=` should not be in the url when not asking for any specific classpath.

2023-03-14 07:28 UTC, efredriksson-modelon commented on tests/impact/client/sal/test_workspace_service.py
> +        assert get_all_experiments.adapter.called
Can you also add a test where `experiments_get` is called with a class_path?

2023-03-14 09:11 UTC, abhilash-kumar-nair commented
Thanks for the review @efredriksson-modelon . I have made the suggested changes!

2023-03-29 05:04 UTC, abhilash-kumar-nair commented
> From the discussion I still think it is unclear what the use case is. Depending on this you could either do it like this or have it on the model class:
> 
> ```
> model = workspace.get_model(...)
> model.get_experiments()
> ```
> 
> If we could have some end-user script on how this feature would be used I think it would become more apparent which solution is most intuitive.

I agree. Thanks for the ideas Emil. I have now made this change. I am not sure, how much will this be helpful for the user.

2023-04-18 06:43 UTC, iakovn commented
> From the discussion I still think it is unclear what the use case is. Depending on this you could either do it like this or have it on the model class:
> ```
> model = workspace.get_model(...)
> model.get_experiments()
> ```
> 
> If we could have some end-user script on how this feature would be used I think it would become more apparent which solution is most intuitive.

Let me try to explain the use case a bit more. We currently only have "full forward flow":
```
model = workspace.get_model(...)
experiment_definition = model.new_experiment_definition(dynamic)
exp = workspace.execute(experiment_definition).wait()
do_postprocessing(exp)
```
The missing part is "restarted" flow:
```
model = workspace.get_model(...)
experiment_definition = model.new_experiment_definition(dynamic)
exps = workspace.get_experiments(class_name)
exp = None
for e  in exps:
   if is_this_matching_my_analysis(e, experiment_definition):
      exp = e
      break
if not exp:
    exp = workspace.execute(experiment_definition).wait()
do_postprocessing(exp)
```

2023-04-18 16:48 UTC, abhilash-kumar-nair commented
> get_experiments

Thanks for the comments @iakovn . I have now moved the method to the workspace entity.

2023-04-20 07:08 UTC, abhilash-kumar-nair commented
> From the discussion I still think it is unclear what the use case is. Depending on this you could either do it like this or have it on the model class:
> 
> ```
> model = workspace.get_model(...)
> model.get_experiments()
> ```
> 
> If we could have some end-user script on how this feature would be used I think it would become more apparent which solution is most intuitive.

Hej @efredriksson-modelon , I was not able to implement the above suggestion due to a circular import(See https://jenkins.modelon.com/internal/blue/organizations/jenkins/WAMSTeam%2Fimpact-client-python/detail/experiment-for-model/8/pipeline/ for the failure), so I have now moved the functionality now to the workspace entity.

2023-04-24 16:34 UTC, iakovn approved these changes
I'm find with this implementation. I do not have a strong opinion if we should have `model.get_experiments()`, `workspace.get_experiments(class_path)` or both as it seems that different flows maybe relevant depending on the specific workflow.

2023-04-25 11:41 UTC, merged