Add docs
modelon-community/impact-client-python pull request #181
Opened 2023-03-27 11:30 UTC by abhilash-kumar-nair

2023-03-27 14:25 UTC, efredriksson-modelon requested changes
:+1:

2023-03-27 14:25 UTC, efredriksson-modelon commented on docs/source/setup.rst
> +This page explains how to authenticate login to the Modelon Impact server from the Python client
`authenticate login` does not sound right. Maybe `authenticate and login`?

2023-03-27 14:33 UTC, abhilash-kumar-nair commented
@efredriksson-modelon Thanks for the review. Blame the AI that paraphrased my sentences :D

2023-03-28 08:42 UTC, iakovn approved these changes
Looks real nice! 🍎  Just a minor comment on using save URL

2023-03-28 08:42 UTC, iakovn commented on docs/source/authentication_with_modelon_impact.rst
> +go to the JupyterHub token manager (located at "https://impact.modelon.cloud/token").
I suggest using `https://impact.modelon.cloud/hub/token` everywhere for consistency (both work)

2023-03-28 10:26 UTC, merged