fix: added docstrings for status
modelon-community/impact-client-python pull request #218
Opened 2023-06-06 03:56 UTC by abhilash-kumar-nair

This PR adds docstrings for Status

2023-06-07 09:08 UTC, iakovn requested changes
Please add documentation on the `run_info.status` property explaining that users should instead get the operation status (and not case/experiment entity status) for tracing status changes of a running simulation.

2023-06-07 12:39 UTC, abhilash-kumar-nair commented
> Please add documentation on the `run_info.status` property explaining that users should instead get the operation status (and not case/experiment entity status) for tracing status changes of a running simulation.

@iakovn Ah I had missed that. Fixed it. Thanks!

2023-06-07 14:10 UTC, abhilash-kumar-nair commented on modelon/impact/client/entities/case.py
> +        Note: For tracing status changes of a running case execution,
I mainly looked at help() function docs. But I agree it makes sense to make it look nice in RTD too. Fixed it :)

2023-06-08 06:33 UTC, iakovn approved these changes
Nice improvement! 👍

2023-06-08 06:47 UTC, merged