chore: reorder docs and rename Class based workflow to Model based workflow
modelon-community/impact-client-python pull request #321
Opened 2024-11-21 13:23 UTC by abhilash-kumar-nair

2024-11-21 15:50 UTC, iakovn requested changes
Thanks for starting this! 🍑 

Please also rename "Class name" into "Model class name" in:
- `modelon/impact/client/entities/model.py`
- `modelon/impact/client/entities/interfaces/model.py`

2024-11-22 02:33 UTC, abhilash-kumar-nair commented
> Thanks for starting this! 🍑
> 
> Please also rename "Class name" into "Model class name" in:
> 
> * `modelon/impact/client/entities/model.py`
> * `modelon/impact/client/entities/interfaces/model.py`

Good catch! Fixed it! Thanks. :)

2024-11-22 07:40 UTC, iakovn requested changes
Minor tweaking and please update the tests.

2024-11-22 07:40 UTC, iakovn commented on docs/source/quick_start.rst
> +   # Get model class
Get model reference. ("class" may be confusing)

2024-11-22 07:40 UTC, iakovn commented on modelon/impact/client/entities/interfaces/model.py
> +        """Model class name."""
Sorry for confusion, drop the "class", just "Model name."

2024-11-22 07:40 UTC, iakovn commented on modelon/impact/client/entities/model.py
> +        """Model class name."""
Model name.

2024-11-22 14:04 UTC, abhilash-kumar-nair commented
> Minor tweaking and please update the tests.

Fixed it now! Thanks!

2024-11-22 14:51 UTC, iakovn requested changes
Unsure about `get_class_name` vs `get_model_name` for the method name.

2024-11-22 14:51 UTC, iakovn commented on modelon/impact/client/entities/experiment.py
> +        """Return the model name."""
Given the name of the method the docstring would be unexpected (while `model class name` is ok-ish) . Shall we **add** `get_model_name` and eventually deprecate `get_class_name` (keep for awhile anyway)?

2024-11-22 14:51 UTC, iakovn commented on modelon/impact/client/entities/model_executable.py
> +        """Return the model name."""
same

2024-11-27 11:13 UTC, abhilash-kumar-nair commented
> Unsure about `get_class_name` vs `get_model_name` for the method name.

Fixed it! Thanks!

2024-11-27 12:23 UTC, iakovn requested changes
some more polishing

2024-11-27 12:23 UTC, iakovn commented on modelon/impact/client/entities/model_executable.py
> +        """Returns the model name."""
Deprecate and add "model_name" property.

2024-11-27 12:23 UTC, iakovn commented on modelon/impact/client/entities/model_executable.py
> +        """Deprecated, use 'get_model_name' attribute."""
"""Deprecated, use 'get_model_name' method."""

2024-11-27 12:23 UTC, iakovn commented on modelon/impact/client/entities/model_executable.py
> +        logger.warning("This attribute is deprectated, use 'get_model_name' instead!")
How about :
```
import warnings
@warnings.deprecated("The 'get_class_name' is deprecated, use 'get_model_name'")
def get_class_name(self) -> str:
```
if you think this is too much then please fix the spelling of deprec**t**ated

2024-11-28 08:03 UTC, abhilash-kumar-nair commented
> some more polishing

Good catch! :microscope: ! I have updated the code now.  there is no @warnings.deprecated unfortunately. I have switched to warnings.warn instead

2024-11-28 09:50 UTC, iakovn approved these changes
Looking good! ✈️

2024-11-28 10:20 UTC, merged