fix: Grammar/font fixes
modelon-community/impact-client-python pull request #59
Opened 2020-09-24 10:08 UTC by abhilash-kumar-nair

2020-09-24 14:25 UTC, abhilash-kumar-nair commented
@efredriksson-modelon , @jacobtaxen , Fixes some of the issues reported - See the updated docs here - https://modelon-impact-client.readthedocs.io/en/minor-doc-fixes/index.html

2020-09-25 08:06 UTC, jacobtaxen requested changes
Very good, it's so satisfying to see spelling errors being removed

2020-09-25 08:06 UTC, jacobtaxen commented on docs/source/setup.rst
> +argument in an interactive mode:
I think "in interactive mode" or "in the interactive mode" fits better here

2020-09-25 08:06 UTC, jacobtaxen commented on docs/source/tutorial.rst
While you're at it, could you remove the comma in "There are different analysis methods, one can choose from" on line 36?

2020-09-25 11:26 UTC, jacobtaxen approved these changes

2020-09-25 12:02 UTC, merged