chore: Added docs for extension feature
modelon-community/impact-client-python pull request #70
Opened 2020-10-23 14:26 UTC by abhilash-kumar-nair

Docs for the extension feature
@jacobtaxen

2020-10-26 14:41 UTC, jacobtaxen commented on docs/source/tutorial.rst
> +could only be setup with one of the two methods. However, it is allowed to call the  ``with_modifiers`` method on the
setup -> set up

2020-10-26 14:41 UTC, jacobtaxen commented on docs/source/tutorial.rst
> +set in both ``experiment_definition`` and extensions, the one set in the extensions would gain precedence override the former.
gain precedence override the former -> gain precedence, overriding the former

2020-10-26 14:41 UTC, jacobtaxen commented on docs/source/tutorial.rst
> +approaches listed below:
this sentence feels a bit weird, maybe "Following either of the approaches listed below, the created experiment definition can be modified to set up a series of simulations" or something

2020-11-03 10:01 UTC, efredriksson-modelon requested changes
Nice 👍 Just a comment about how much focus we should put on the specific range operator.

2020-11-03 10:59 UTC, abhilash-kumar-nair commented on docs/source/quick_start.rst
> +A more flexible and customized way to define a series of simulations::
The two colons signify a code block below :)

2020-11-03 13:24 UTC, efredriksson-modelon approved these changes
👍

2020-11-03 15:25 UTC, jacobtaxen approved these changes
Looks good!

2020-11-04 08:09 UTC, merged