feat: Added support for choices operator
modelon-community/impact-client-python pull request #71
Opened 2020-12-22 12:47 UTC by abhilash-kumar-nair

2021-01-07 11:55 UTC, efredriksson-modelon requested changes
Nice addition 👍

Minor, but I think the documentation can be clarified by being more precise on what 'custom' here means.

2021-01-07 11:55 UTC, efredriksson-modelon commented on modelon/impact/client/experiment_definition.py
> +    Choices operator class for parameterizing custom batch runs.
remove 'custom'

2021-01-07 11:55 UTC, efredriksson-modelon commented on modelon/impact/client/experiment_definition.py
> +            'inertia2.J': Choices(0.1, 0.5)}, k=2, w=7)
maybe just `({'inertia2.J': Choices(0.1, 0.5)})` to make the exmple easier to grasp?

2021-01-07 11:55 UTC, efredriksson-modelon commented on docs/source/tutorial.rst
> +It is also possible to create multi-execution experiments with custom parameter values to sweep::
`custom` -> `an explicit list (choices) of`

2021-01-07 11:55 UTC, efredriksson-modelon commented on docs/source/tutorial.rst
> +Here the ``Choices()`` operator class is used to specify custom values for the parameter to sweep. The parametrization in the
`custom` -> `an explicit list of`

2021-01-07 11:55 UTC, efredriksson-modelon commented on docs/source/tutorial.rst
> +examples above would configure a set of four simulation cases for the fmu with ``4`` custom values for the ``PI.k`` parameter.
custom -> choosen

2021-01-07 11:55 UTC, efredriksson-modelon commented on docs/source/tutorial.rst
> +It also possible to have use a combination of range and choices operator to setup a batch run::
remove 'have'

2021-01-08 06:56 UTC, abhilash-kumar-nair commented
> Nice addition 👍
> 
> Minor, but I think the documentation can be clarified by being more precise on what 'custom' here means.

@efredriksson-modelon , Thanks for the review! :) I have made the suggested the changes. Could you please take another look?

2021-01-08 08:10 UTC, efredriksson-modelon approved these changes
👍

2021-01-08 08:34 UTC, merged