fix: Corrected the upload_workspace api
modelon-community/impact-client-python pull request #72
Opened 2020-12-23 07:56 UTC by abhilash-kumar-nair

This PR fixes the upload workspace API. The issue was the import workspace API takes form-data as the request body type but was given JSON request type.

2021-01-07 09:59 UTC, jacobtaxen approved these changes
Looks good and works fine

2021-01-07 12:46 UTC, efredriksson-modelon requested changes
I am a little confused as the 'Form' classes/methods are not used.

2021-01-07 12:46 UTC, efredriksson-modelon commented on modelon/impact/client/sal/service.py
> +class FormDataResponse(Response):
This class is not used anywhere?

2021-01-07 12:46 UTC, efredriksson-modelon commented on modelon/impact/client/sal/service.py
> +    def post_form_data(self, url):
This method is not used anywhere?

2021-01-08 12:48 UTC, abhilash-kumar-nair commented
> I am a little confused as the 'Form' classes/methods are not used.

@efredriksson-modelon , You are right! The response body would be still be a JSON, so the only issue was  the additional workspace Id argument . I have made the correction now. Thanks!

2021-01-08 14:16 UTC, efredriksson-modelon approved these changes
👍

2021-01-11 04:14 UTC, merged