fix: Removed kwargs argument as we only need to support 'qualified' v…
modelon-community/impact-client-python pull request #73
Opened 2021-01-04 07:34 UTC by abhilash-kumar-nair

Removed possibility to set variable modifiers as key-worded arguments to experiment definition.

2021-01-07 13:13 UTC, efredriksson-modelon requested changes
This will be a breaking change so unless there is a mayor gain for this change, I don't think we should do this.

If there is a usability problem, we should update the documentation. If we really don't like this form of giving modifiers, we could remove all traces of it from the documentation but keep the implementation. A middle way could be to ensure the examples all use the preferred way, so the reader only need to take in one way of specifying modifiers.

2021-01-19 07:17 UTC, abhilash-kumar-nair commented
> This will be a breaking change so unless there is a mayor gain for this change, I don't think we should do this.
> 
> If there is a usability problem, we should update the documentation. If we really don't like this form of giving modifiers, we could remove all traces of it from the documentation but keep the implementation. A middle way could be to ensure the examples all use the preferred way, so the reader only need to take in one way of specifying modifiers.

@efredriksson-modelon, I have removed **kwargs** from the docs and also added a deprecation warning. However I have still kept the usage in the test,  we have for the 'with_modifier' function. I feel we should have them tested until we finally deprecate them in a future release. What do you think?

2021-01-19 09:28 UTC, efredriksson-modelon requested changes
We also need to update the sphinx documentation.

2021-01-19 09:28 UTC, efredriksson-modelon commented on modelon/impact/client/experiment_definition.py
> +logging.basicConfig(level=logging.INFO)
remove

2021-01-19 09:28 UTC, efredriksson-modelon commented on modelon/impact/client/experiment_definition.py
> +            logger.info(
info -> warning

2021-01-19 09:28 UTC, efredriksson-modelon commented on modelon/impact/client/experiment_definition.py
> +            logger.info(
info -> warning

2021-01-19 14:14 UTC, efredriksson-modelon approved these changes
👍

2021-01-25 12:55 UTC, merged